application: pitt-course-scheduler
version: 2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: css
  mime_type: "text/css"
  
- url: /js
  static_dir: js
  mime_type: "application/javascript"
  
- url: /classes
  static_dir: classes
  mime_type: "application/json"
  application_readable: true

- url: /.*
  script: code.app
  
libraries:
- name: django
  version: "latest"